### ISSUE TITLE
Error File not found 'app.exe'

### ISSUE THREAD

**Issue by crashbdx** [electron-userland/electron-installer-windows#247]
**What version of `electron-installer-windows` are you using?**
1.1.0
**What version of `node` and `npm` are you using?**
8.12.0
**What operating system are you using?**
WIN 10

Getting this error when trying to build installer:

```
> electron-installer-windows --src release-builds/wallet-win32-ia32/ --dest release-builds/installers/win/ --config config.json

Creating package (this may take a while)
Error: Error creating package with NuGet: Error executing command (Exited with status 1):
G:\WORK\REPO\wallet\node_modules\electron-installer-windows\vendor\nuget\NuGet.exe pack C:\Users\edge\AppData\Local\Temp\electron-14000mz1pYwUZeDPV\App-edge_0.5.0\nuget\App-edge.nuspec -BasePath C:\Users\edge\AppData\Local\Temp\electron-14000mz1pYwUZeDPV\App-edge_0.5.0\App-edge -OutputDirectory C:\Users\edge\AppData\Local\Temp\electron-14000mz1pYwUZeDPV\App-edge_0.5.0\nuget -NoDefaultExcludes
File not found: 'App-edge.exe'.

    at err (G:\WORK\REPO\wallet\node_modules\electron-installer-windows\src\installer.js:31:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) 'Error: Error creating package with NuGet: Error executing command (Exited with status 1):\nG:\\WORK\\REPO\\wallet\\node_modules\\electron-installer-windows\\vendor\\nuget\\NuGet.exe pack C:\\Users\\edge\\AppData\\Local\\Temp\\electron-14000mz1pYwUZeDPV\\App-edge_0.5.0\\nuget\\App-edge.nuspec-BasePath C:\\Users\\edge\\AppData\\Local\\Temp\\electron-14000mz1pYwUZeDPV\\App-edge_0.5.0\\App-edge -OutputDirectory C:\\Users\\edge\\AppData\\Local\\Temp\\electron-14000mz1pYwUZeDPV\\App-edge_0.5.0\\nuget -NoDefaultExcludes\nFile not found: \'App-edge.exe\'.\r\n\n    at err (G:\\WORK\\REPO\\wallet\\node_modules\\electron-installer-windows\\src\\installer.js:31:11)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! App-edge@0.5.0 inst-win: `electron-installer-windows --src release-builds/wallet-win32-ia32/ --dest release-builds/installers/win/ --config config.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the App-edge@0.5.0 inst-win script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\edge\AppData\Roaming\npm-cache\_logs\2019-01-17T04_36_09_748Z-debug.log
```

**Comment by crashbdx** [comment]
Humm, look like it is related to the packaging with asar option on, then electron-windows-installer doesnt find the ressources/app folder, will try without asar then.

**Comment by fcastilloec** [comment]
I'm 99% sure that this is not an issue, it's related to the name of your app.
This app works 100% with asar and without it. You'll probably get the same error without asar.
Also, it'll be very helpful if you give us the output of running the command with `DEBUG=electron-installer-windows`

**Comment by crashbdx** [comment]
Thats actually why i thought it was related with asar because the debug output give me that:

```
$ DEBUG=electron-installer-windows electron-installer-windows --src release-builds/wallet-win32-ia32/ --dest release-builds/installers/win
Creating package (this may take a while)
2019-01-17T04:30:23.631Z electron-installer-windows Reading package metadata from release-builds\wallet-win32-ia32\resources\app\package.json
2019-01-17T04:30:23.632Z electron-installer-windows Error creating package: Error reading package metadata: release-builds\wallet-win32-ia32\resources\app\package.json: ENOENT: no such file or directory, open 'C:\Users\edge\release-builds\wallet-win32-ia32\resources\app\package.json'
Error: Error reading package metadata: release-builds\wallet-win32-ia32\resources\app\package.json: ENOENT: no such file or directory, open 'C:\Users\edge\release-builds\wallet-win32-ia32\resources\app\package.json'
    at err (C:\Users\edge\AppData\Roaming\npm\node_modules\electron-installer-windows\src\installer.js:31:11)
    at <anonymous> 'Error: Error reading package metadata: release-builds\\wallet-win32-ia32\\resources\\app\\package.json: ENOENT: no such file or directory, open \'C:\\Users\\edge\\release-builds\\wallet-win32-ia32\\resources\\app\\package.json\'\n    at err (C:\\Users\\edge\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\src\\installer.js:31:11)\n    at <anonymous>'
```

But now that i paste it here, i realise the it is loocking for my release-builds folder on C:/Users/edge/ when it is not at all where it is :) And you are right, same error without asar.

Any idea why this:

```
"inst-win": "electron-installer-windows --src release-builds/wallet-win32-ia32/ --dest release-builds/installers/win/ --config config.json"
```
Is looking for the folder at the root of C and not the root of the package.json

**Comment by crashbdx** [comment]
here how i package first with electron-packager:

"package-win": "electron-packager . wallet --overwrite --asar --platform=win32 --arch=ia32 --icon=assets/build/win/icon.ico --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName=\"Wallet 0.5\"",

**Comment by crashbdx** [comment]
this is what is not found: \resources\app\package.json :/

**Comment by fcastilloec** [comment]
As I suspected, you probably didn't read the whole README for `electron-packager`, neither our README. In [from the command line](https://github.com/electron-userland/electron-packager#from-the-command-line) section in `electron-packager`, it says that running `electron-packager <sourcedir> <appname>` gives
> ... create a app in \<out>/\<appname>-\<platform>-\<arch> ...

Whis is also mentioned in the `Usage` and `Command line` sections of this module.

You have to run `electron-installer-windows --src release-builds/wallet-win32-ia32`

**Comment by fcastilloec** [comment]
I'm assuming you're running both commands from the same directory, right?
Can you confirm that `wallet-win32-ia32` directory exists and that there's a `resources/app.asar` in there?

PS: Sorry, didn't mean to close the issue, just pushed the wrong button.

**Comment by crashbdx** [comment]
Thanks for the help, yes i confirm that wallet-win32-ia32 directory exists and that there's a resources/app.asar in there.

**Comment by fcastilloec** [comment]
Can you compile the example? Just follow the issue template (it's there for a reason :smile:)
If you also have errors there, then there's something very weird happend. If there's no errors, can you give `electron-installer-windows` the full path rather than a relative one?

**Comment by fcastilloec** [comment]
Coul you please run `npm install` before running `DEBUG='electron-installer-windows' npm run build`?

Let's move this discussion here: https://webchat.freenode.net/ put any nickname you want, and for the channel `electron-installer`

**Comment by crashbdx** [comment]
Thanks a lot for the help, i needs to get away for 40min, ill be back after sorry :)
