### ISSUE TITLE
`File not found: 'gpb.exe'.` when executing electron-installer-windows 

### ISSUE THREAD

**Issue by eegabeeva** [electron-userland/electron-installer-windows#251]
**What version of `electron-installer-windows` are you using?**
1.1.0

**What version of `node` and `npm` are you using?**
node 10.6.0 
npm 6.1.0

**What operating system are you using?**
Windows 10 

**Can you compile the [example app](https://github.com/electron-userland/electron-installer-windows/tree/master/example) successfully?**
Yes

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
No configuration. Just installed `electron-installer-windows` and tried a first run.

`npm run setup`, `setup` defined as:
"setup": "electron-installer-windows --src client_builds/windows/app-win32-x64/ --dest client_builds/installers/"

**What did you expect to happen?**
A successfully generated installer or a debuggable error message.

**What actually happened?**
```
C:\Users\1411195\source\repos\Vale-Support-Missing\InternalWebApp>npm run setup

> gpb@1.1.0 setup C:\Users\1411195\source\repos\Vale-Support-Missing\InternalWebApp
> electron-installer-windows --src client_builds/windows/app-win32-x64/ --dest client_builds/installers/

Creating package (this may take a while)
Error: Error creating package with NuGet: Error executing command (Exited with status 1):
C:\Users\1411195\source\repos\Vale-Support-Missing\InternalWebApp\node_modules\electron-installer-windows\vendor\nuget\NuGet.exe pack C:\Users\1411195\AppData\Local\Temp\electron-26040vWwCX0OTsyo0\gpb_1.1.0\nuget\gpb.nuspec -BasePath C:\Users\1411195\AppData\Local\Temp\electron-26040vWwCX0OTsyo0\gpb_1.1.0\gpb -OutputDirectory C:\Users\1411195\AppData\Local\Temp\electron-26040vWwCX0OTsyo0\gpb_1.1.0\nuget -NoDefaultExcludes
File not found: 'gpb.exe'.

    at err (C:\Users\1411195\source\repos\Vale-Support-Missing\InternalWebApp\node_modules\electron-installer-windows\src\installer.js:31:11)
    at process._tickCallback (internal/process/next_tick.js:68:7) 'Error: Error creating package with NuGet: Error executing command (Exited with status 1):\nC:\\Users\\1411195\\source\\repos\\Vale-Support-Missing\\InternalWebApp\\node_modules\\electron-installer-windows\\vendor\\nuget\\NuGet.exe pack C:\\Users\\1411195\\AppData\\Local\\Temp\\electron-26040vWwCX0OTsyo0\\gpb_1.1.0\\nuget\\gpb.nuspec -BasePath C:\\Users\\1411195\\AppData\\Local\\Temp\\electron-26040vWwCX0OTsyo0\\gpb_1.1.0\\gpb -OutputDirectory C:\\Users\\1411195\\AppData\\Local\\Temp\\electron-26040vWwCX0OTsyo0\\gpb_1.1.0\\nuget -NoDefaultExcludes\nFile not found: \'gpb.exe\'.\r\n\n    at err (C:\\Users\\1411195\\source\\repos\\Vale-Support-Missing\\InternalWebApp\\node_modules\\electron-installer-windows\\src\\installer.js:31:11)\n    at process._tickCallback (internal/process/next_tick.js:68:7)'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gpb@1.1.0 setup: `electron-installer-windows --src client_builds/windows/app-win32-x64/ --dest client_builds/installers/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gpb@1.1.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\1411195\AppData\Roaming\npm-cache\_logs\2019-02-11T18_49_57_858Z-debug.log
```

**Comment by eegabeeva** [comment]
Couldn't find out what `gpb.exe` is supposed to be or how/where to install it.

**Comment by fcastilloec** [comment]
`gpb.exe` is the name of the executable you've created with `electron-packager`, this is also seen in the log because we're trying to use `gdp.nuspec` to build the windows installer, which is related to the name of your app.
There's an `options.exe` undocumented option (we'll fix this shortly, I'm on holidays now so it'll take a while), you can specify the executable for your project there. See https://github.com/electron-userland/electron-installer-windows/issues/248
