### ISSUE TITLE
"TypeError: expected author to be a string" in my app & electron-installer-windows/example

### ISSUE THREAD

**Issue by dsmithhfx** [electron-userland/electron-installer-windows#270]
**What version of `electron-installer-windows` are you using?**
1.1.1
**What version of `node` and `npm` are you using?**
8.10.0, 3.5.2
**What operating system are you using?**
Ubuntu 18.04
**Can you compile the [example app](https://github.com/electron-userland/electron-installer-windows/tree/master/example) successfully?**
No
**If not, paste here the output of the following commands:**
$ DEBUG='electron-installer-windows' npm run build

> poopie@0.0.1 build /home/dewartestserver/dev/electron-installer-windows/example
> npm run clean && npm run exe32 && npm run set32 && npm run exe64 && npm run set64

> poopie@0.0.1 clean /home/dewartestserver/dev/electron-installer-windows/example
> rimraf dist

> poopie@0.0.1 exe32 /home/dewartestserver/dev/electron-installer-windows/example
> electron-packager . poopie --platform win32 --arch ia32 --out dist/ --icon resources/Icon.ico

Packaging app for platform win32 ia32 using electron v4.1.4
Wrote new app to dist/poopie-win32-ia32

> poopie@0.0.1 set32 /home/dewartestserver/dev/electron-installer-windows/example
> electron-installer-windows --src dist/poopie-win32-ia32/ --dest dist/installers/ia32/ --config config.json

Creating package (this may take a while)
  electron-installer-windows Reading package metadata from dist/poopie-win32-ia32/resources/app/package.json +0ms
  electron-installer-windows Error creating package: expected author to be a string +3ms
TypeError: expected author to be a string
    at module.exports (/usr/local/lib/node_modules/electron-installer-windows/node_modules/parse-author/index.js:14:11)
    at common.readMetadata.then.pkg (/usr/local/lib/node_modules/electron-installer-windows/src/installer.js:121:26)
    at <anonymous> 'TypeError: expected author to be a string\n    at module.exports (/usr/local/lib/node_modules/electron-installer-windows/node_modules/parse-author/index.js:14:11)\n    at common.readMetadata.then.pkg (/usr/local/lib/node_modules/electron-installer-windows/src/installer.js:121:26)\n    at <anonymous>'

npm ERR! Linux 4.15.0-36-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "set32"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! poopie@0.0.1 set32: `electron-installer-windows --src dist/poopie-win32-ia32/ --dest dist/installers/ia32/ --config config.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the poopie@0.0.1 set32 script 'electron-installer-windows --src dist/poopie-win32-ia32/ --dest dist/installers/ia32/ --config config.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the poopie package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-installer-windows --src dist/poopie-win32-ia32/ --dest dist/installers/ia32/ --config config.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs poopie
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls poopie
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dewartestserver/dev/electron-installer-windows/example/npm-debug.log

npm ERR! Linux 4.15.0-36-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! poopie@0.0.1 build: `npm run clean && npm run exe32 && npm run set32 && npm run exe64 && npm run set64`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the poopie@0.0.1 build script 'npm run clean && npm run exe32 && npm run set32 && npm run exe64 && npm run set64'.

[omitted some final boilerplate]

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
in project folder: npm install --save-dev electron-installer-windows
package.json:
{
  "name": "safety-valve-cache-testing",
  "productName": "Safety valve app-srv",
  "version": "0.1.2",
  "main": "main.js",
  "devDependencies": {
    "electron": "^4.1.1",
    "electron-cli": "^0.2.8",
    "electron-installer-windows": "^1.1.1",
    "electron-packager": "^13.1.1"
  },
  "scripts": {
    "package-mac": "electron-packager . --overwrite --platform=darwin --arch=x64 --icon=assets/icons/mac/icon.icns --prune=true --ignore=assets --out=release-builds",
    "package-win": "electron-packager . safety-valve-training-tool --overwrite --asar=true --platform=win32 --arch=all --icon=assets/icons/win/icon.ico --prune=true --ignore=assets --out=release-builds --version-string.CompanyName=Dewar --version-string.FileDescription=Dewar --version-string.ProductName=\"Safety Valve Cache Testing\"",
    "package-linux": "electron-packager . safety-valve-training-tool --overwrite --asar=true --platform=linux --arch=x64 --icon=assets/icons/png/1024x1024.png --prune=true --ignore=assets --out=release-builds",
    "setup-win32": "electron-installer-windows --src release-builds/safety-valve-training-tool-win32-ia32 --dest release-builds/installers/win32",
    "setup-win64": "electron-installer-windows --src release-builds/safety-valve-training-tool-win32-ia64 --dest release-builds/installers/win64"
  },
  "author": {
    "name": "Dewarcommunications",
    "email": "[removed]",
    "url": "[removed]"
  }
}
----------
^^^ Note "author": "name": is one string.
npm run setup-win32
**What did you expect to happen?**
Compile a windows installer exe into  [project]/release-builds/installers/win32/
**What actually happened?**
Similar "TypeError: expected author to be a string [...]" as above output of electron-installer-windows/example (!) and mentioned in prior issue(s) -- as previously reported, changing the name to a string (no spaces) does not fix the issue.

Edit: OK, I misunderstood the "string" thing (package.json "author" stuff should be on one line without brackets per "https://docs.npmjs.com/files/package.json#people-fields-author-contributors".

After fixing that, I'm now getting a mono "Error creating package with NuGet"

**Comment by dsmithhfx** [comment]
Built a package after sifting through a lot of errors and fixing them.
