### ISSUE TITLE
Error NU5019: File not found: 'LICENSE'

### ISSUE THREAD

**Issue by realrecordzLab** [electron-userland/electron-installer-windows#332]
I'm using the latest version of this nice package. I need to build an installer for an electron app created with electron-builder form vue ui. Anyway I always get this error after the `electron-installer-windows`command is given into macOS terminal:

```
Creating package (this may take a while)
ExitCodeError: Command failed with a non-zero return code (1):
mono /usr/local/lib/node_modules/electron-installer-windows/vendor/nuget/nuget.exe pack /var/folders/4z/pbf5z13d7qxb207y7w3br8wm0000gn/T/electron-installer--72450-as30qUAoE2Iy/file_shield_1.0.0_undefined/nuget/file_shield.nuspec -BasePath /var/folders/4z/pbf5z13d7qxb207y7w3br8wm0000gn/T/electron-installer--72450-as30qUAoE2Iy/file_shield_1.0.0_undefined/file_shield -OutputDirectory /var/folders/4z/pbf5z13d7qxb207y7w3br8wm0000gn/T/electron-installer--72450-as30qUAoE2Iy/file_shield_1.0.0_undefined/nuget -NoDefaultExcludes
Componendo pacchetto da'file_shield.nuspec'.

Error NU5019: File not found: 'LICENSE'.
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/electron-installer-windows/node_modules/@malept/cross-spawn-promise/dist/src/index.js:99:24)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12) {
  cmd: 'mono',
  args: [
    '/usr/local/lib/node_modules/electron-installer-windows/vendor/nuget/nuget.exe',
    'pack',
    '/var/folders/4z/pbf5z13d7qxb207y7w3br8wm0000gn/T/electron-installer--72450-as30qUAoE2Iy/file_shield_1.0.0_undefined/nuget/file_shield.nuspec',
    '-BasePath',
    '/var/folders/4z/pbf5z13d7qxb207y7w3br8wm0000gn/T/electron-installer--72450-as30qUAoE2Iy/file_shield_1.0.0_undefined/file_shield',
    '-OutputDirectory',
    '/var/folders/4z/pbf5z13d7qxb207y7w3br8wm0000gn/T/electron-installer--72450-as30qUAoE2Iy/file_shield_1.0.0_undefined/nuget',
    '-NoDefaultExcludes'
  ],
  stdout: "Componendo pacchetto da'file_shield.nuspec'.\n",
  stderr: "Error NU5019: File not found: 'LICENSE'.\n",
  code: 1
} Error: Command failed with a non-zero return code (1):
mono /usr/local/lib/node_modules/electron-installer-windows/vendor/nuget/nuget.exe pack /var/folders/4z/pbf5z13d7qxb207y7w3br8wm0000gn/T/electron-installer--72450-as30qUAoE2Iy/file_shield_1.0.0_undefined/nuget/file_shield.nuspec -BasePath /var/folders/4z/pbf5z13d7qxb207y7w3br8wm0000gn/T/electron-installer--72450-as30qUAoE2Iy/file_shield_1.0.0_undefined/file_shield -OutputDirectory /var/folders/4z/pbf5z13d7qxb207y7w3br8wm0000gn/T/electron-installer--72450-as30qUAoE2Iy/file_shield_1.0.0_undefined/nuget -NoDefaultExcludes
Componendo pacchetto da'file_shield.nuspec'.

Error NU5019: File not found: 'LICENSE'.
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/electron-installer-windows/node_modules/@malept/cross-spawn-promise/dist/src/index.js:99:24)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)
```

Is there any fix?

**Comment by fcastilloec** [comment]
Sorry, but you should check with `electron-builder` and not here to what's going on. To use this module directly, you usually need the output from `electron-packager` which will include the LICENSE file that seems missing from the error log.
